### ISSUE TITLE
RTTI for the published method "Test1" of class "TMyClass" has 38 extra bytes of unknown data!

### ISSUE THREAD

**Issue by jpluimers** [jpluimers/HVRTTIUtils#1] opened 2017-03-11 19:09 UTC
Error message:

```
RTTI for the published method "Test1" of class "TMyClass" has 38 extra bytes of unknown data!
```

Generated by both below projects when using Delphi 2007:

- TestPublishedMethodParams
- TestMorePubMethodParams

See also the comments at https://hallvards.blogspot.nl/2006/05/hack-10-getting-parameters-of.html

**Comment by hvassbotn** [comment] 2017-03-13 08:45
Caused by PChar-casts that should be made into PAnsiChar-casts.

**Comment by hvassbotn** [comment] 2017-03-13 09:07
Fix for this included in pull request (that works in XE6 at least) :)

**Comment by jpluimers** [comment] 2017-03-14 11:39
Note that pull request #3 didn't fix this.

**Comment by hvassbotn** [comment] 2017-03-14 12:13
Right. Probably some more RTTI there that we don't read yet. As long as the code and RTTI we do use work, we can probably ignore this for now? 

Will have a second look, though.

**Comment by jpluimers** [comment] 2017-03-27 22:33
Fixed by https://github.com/jpluimers/HVRTTIUtils/commit/bed06e98909ed6f9f5c6c32179e330e14b7ee8d5

- Delphi 2010 and newer maintain a Tail.ParameterCount which results the IF structure coming down to
   1. an if when there are no parameters (I'm not sure this can even happen)
   2. a for loop involving TailParameterCount counting the size of all parameters (and attributes)
- Delphi 2009 and older lack the Tail.ParameterCount so we have a while loop that counts the bytes used by the parameters and stops as soon as we match or exceed the expected Result.Size

**Closed as completed** 2017-03-27 22:33 UTC
